sequencia = 'ACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTATGCGTACGTTAGCTAGATTACAGATTACAGATTACAGATTACAGATTACAGATTACAGATTACAGATTACAGATTACAGATTACAGATTACAGAT'
primer = "ATGCGTACGTTAGCTA" 

if primer in sequencia:
    posicao = sequencia.find(primer)
    print(f"O primer foi encontrado na posição: {posicao}")
else:
    print("O primer não foi encontrado.")
